version: "3.8"

services:
  app:
    build:
      context: .
      target: production
    container_name: pos_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DATABASE_URL=postgresql://r_pos:restaurant_pos1234567@localhost:5432/r_pos
      - JWT_SECRET_KEY=K#8zR2qoJp7@yV!9FgNc*4hGmL6vP5u^3H@X&6sL1wB+T3iA2nC_0sM*O0aG6eE#9lK3oM8xQ@yU8vB4kL1zI7aR!3jE3bG3d
      - BASE_URL=http://localhost:3001
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    command: node dist/server.js
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=r_pos
      - POSTGRES_PASSWORD=restaurant_pos1234567
      - POSTGRES_DB=r_pos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
